
# These bug out and trigger phantom touches on this machine, so disable them
# in X11 startup until we have a better fix.
exec --no-startup-id xinput disable "Wacom HID 5365 Pen eraser"
exec --no-startup-id xinput disable "Wacom HID 5365 Pen stylus"
