# Pi desktop ops (i3-resurrect + quick launches)

# Save/restore current workspace state (layout + programs)
bindsym $mod+Ctrl+s exec --no-startup-id i3-resurrect save
bindsym $mod+Ctrl+r exec --no-startup-id i3-resurrect restore

# Rofi i3 sessions (also available inside combi)
# bindsym $mod+Ctrl+p exec --no-startup-id rofi -show i3sessions

# Quick Firefox
bindsym $mod+Shift+f exec --no-startup-id firefox
